# This config file overrides _config.yml with environmentals required to run on a
# localhost. To preview the site locally, run the following:
#
# `jekyll serve --config _config.yml,_config_dev.yml`
#
# You can also optionally run with the `--watch` flag to avoid having to reload when
# making changes:
#
# `jekyll serve --config _config.yml,_config_dev.yml --watch`

# Localhost overrides
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000/" # the base hostname & protocol for your site
