# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-normal: Cresca Group
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cresca.github.io" # the base hostname & protocol for your site
author:
street_address: 6760 Jimmy Carter Blvd., Suite 140
city: Peachtree Corners
state: GA
zip_code: 30071
country: United States
phone: +1 (770) 558-1753
email: support@crescagroup.com

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://www.facebook.com/Cresca-Group-998903440136075/
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/company/the-cresca-group?trk=mini-profile
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: crescagroup
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo: /assets/images/Logo_Master_White.png
google_site_verification:
